name: daily-json

on:
  schedule:
    # 台灣時間 08:30
    - cron: "30 0 * * *"

    # 台灣時間 21:00
    - cron: "0 13 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install --no-audit --no-fund

      - run: node script/generate_market.js

      - run: node script/generate_today.js
        env:
          FINMIND_TOKEN: ${{ secrets.FINMIND_TOKEN }}

      - run: node script/stats_winrate.js

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add public/*.json public/history/*.json || true

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "auto update data"
          git pull --rebase origin main || true
          git push